add_newline = false

# A minimal left prompt
#format = """$hostname$python$directory$character"""

format = """$hostname$sudo$python${custom.git_root_name}$directory$status${custom.git_bare}${custom.git_repo_name}$git_status$cmd_duration
$character"""

# right side is not supported in Bash
#right_format = """$status$git_branch${custom.git_status_dirty}$git_status"""
#right_format = """$status$cmd_duration$git_branch${custom.git_status_dirty}$git_status"""

palette="wombat"

[hostname]
ssh_only = false
format = '[$hostname](bold blue) '
disabled = false

[sudo]
disabled = false
symbol = "🥷"
format = "[$symbol]($style)"

# [git_branch]
# symbol = " "
# style = "green"
# format = "[❯ ](#767676)[$symbol$branch]($style)"

[custom.git_bare]
command = "echo bare"
symbol = " "
when = "git rev-parse --is-bare-repository 2>/dev/null | grep -q true"
format = "[$symbol$output](bold red) "

[custom.git_repo_name]
command = '''
p=$(git rev-parse --show-toplevel 2>/dev/null) || exit
basename "$p"
'''
symbol = " "
when = "git rev-parse --git-dir 2>/dev/null"
format = "[$symbol$output](bold cyan) "

[custom.git_root_name]
command = '''
p=$(git rev-parse --git-common-dir 2>/dev/null) || exit
p=${p%/.git}
basename "$p"
'''
when = "git rev-parse --is-inside-work-tree 2>/dev/null"
format = "[$output](bold cyan) "

[git_status]
stashed = "[*${count}](blue) "
modified = "[!${count}](yellow) "
staged = "[+${count}](green) "
untracked = "[?${count}](blue) "
deleted = "[-${count}](red) "
format = " ([$stashed$modified$staged$untracked $ahead_behind]($style))"
#format = " ([$all_status $ahead_behind]($style))"

# Define custom colors
[palettes.tokyo_night]
black = '#15161e'
blue = '#7aa2f7'
cyan = '#7dcfff'
green = '#9ece6a'
purple = '#bb9af7'
red = '#f7768e'
white = '#a9b1d6'
yellow = '#e0af68'

[palettes.tokyo_night_256]
black = '16'
blue = '111'
cyan = '117'
green = '149'
purple = '141'
red = '210'
white = '146'
yellow = '179'

[palettes.wombat]
black = '#000000'
blue = '#5da9f6'
cyan = '#82fff7'
green = '#b1e969'
purple = '#e86aff'
red = '#ff615a'
white = '#dedacf'
yellow = '#ebd99c'

[palettes.wombat_256]
black = '0'
blue = '75'
cyan = '123'
green = '149'
purple = '171'
red = '203'
white = '188'
yellow = '223'

[character]
success_symbol = "[❯](purple)[❯](cyan)"
error_symbol = "[❯](yellow)[❯](red)"
vicmd_symbol = "[❮](purple)[❮](cyan)"

[python]
format = '[(\($virtualenv\) )]($style)'
style = 'white'

[directory]
style = "blue"
truncation_length = 3
truncation_symbol = ""
fish_style_pwd_dir_length = 1

[cmd_duration]
format = ' [$duration]($style)'

[line_break]
disabled = true

[status]
disabled = false
symbol = ' ✘'
