autosave 2048

content /home/gal/.snapraid.content
disk DH /home

content /snapraid-drives/data/SRD01/snapraid.content
disk SRD01 /snapraid-drives/data/SRD01

content /snapraid-drives/data/SRD02/snapraid.content
disk SRD02 /snapraid-drives/data/SRD02

content /snapraid-drives/data/SRD03/snapraid.content
disk SRD03 /snapraid-drives/data/SRD03

content /snapraid-drives/data/SRD04/snapraid.content
disk SRD04 /snapraid-drives/data/SRD04

content /snapraid-drives/data/SRD05/snapraid.content
disk SRD05 /snapraid-drives/data/SRD05

content /snapraid-drives/data/SRD06/snapraid.content
disk SRD06 /snapraid-drives/data/SRD06

parity /snapraid-drives/parity/parity1/snapraid.parity
2-parity /snapraid-drives/parity/parity2/snapraid.2-parity
3-parity /snapraid-drives/parity/parity3/snapraid.3-parity

nohidden

exclude *.unrecoverable
exclude lost+found/
exclude aquota.user
exclude aquota.group
exclude swapfile
exclude /tmp/
exclude .content
#exclude *.bak
#exclude *.log
exclude /snapraid.conf*
exclude *.qcow2
exclude *.vmdk # VMWare disk
exclude *.vswp # VMWare swap
exclude *.vmss # VMWare suspend
exclude *.vmsn # VMWare memory snapshot
exclude *.vmem # VMWare paging backup

exclude /noRaid/
exclude /emby-cache/
exclude /download-partial/
exclude .cache/
exclude /gal/.*
exclude /gal/VirtualBoxVMs/
exclude /gal/.config/
exclude /gal/snap/
exclude /gal/plain/
exclude /flatpak-notauser/
exclude /snaps-notauser/
exclude /dockerDefault/
exclude /DockerData/
exclude /gal/code/dotemacs/
exclude /emby/emby-cache/

exclude /gal/code/*/node_modules/
exclude /gal/code/*/bin/
exclude /gal/code/*/obj/
exclude /gal/code/*/*/bin/
exclude /gal/code/*/*/obj/
exclude /gal/code/*/*/*/bin/
exclude /gal/code/*/*/*/obj/
