#!/bin/bash

# set shell language to UTF8
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# fnm (nodejs manager)
FNM_PATH="/home/gal/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$FNM_PATH:$PATH"
  # eval "`fnm env`"
  eval "$(fnm env --use-on-cd)" # automatically switch node version based on directory
fi

# Homebrew
if [ -f "/home/linuxbrew/.linuxbrew/bin/brew" ]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Emacs
alias ec="emacsclient -r -n -a ''"

# bat
alias bat='batcat'

# Rust
if [ -f "$HOME/.cargo/env" ]; then
    . "$HOME/.cargo/env"
fi

# Add .NET Core SDK tools
export PATH="$PATH:/home/gal/.dotnet/tools"

# use starship for the shell prompt
eval "$(starship init bash)"

# opencode
export PATH=/home/gal/.opencode/bin:$PATH
alias opencode="nono run --allow-cwd --profile opencode-dotnet -- opencode"

# eza - modern ls
alias ls="eza"
alias ll="eza -l"

# claude code
alias claude="nono run --profile claude-code-dotnet -- claude"

# zoxide - better cd
eval "$(zoxide init bash)"
