[main]
#font = monospace:size=12
font = Cousine Nerd Font Mono:size=12, monospace:size=12

[text-bindings]
# \x1b[1;5l     = Control+comma
\x1b[1;6A     = Control+Shift+Up
\x1b[1;6B     = Control+Shift+Down